; Description de la configuration (commentaire)
; Exemple de configuration locale
; Chaîne de connexion PDO (hôte, base, encodage)
; Nom d'utilisateur de la base de données

DB_NAME = "ecommerce_mvc"
DB_HOST = "127.0.0.1"
DB_USERNAME = "postgres"
DB_PASSWORD = "azerty"
DB_PORT = 5432

